CREATE DATABASE IF NOT EXISTS notes_app_magic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE notes_app_magic;

CREATE TABLE folders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  parent_id INT NULL,
  name VARCHAR(255) NOT NULL,
  position INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES folders(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  folder_id INT NOT NULL,
  title VARCHAR(255) DEFAULT '',
  content TEXT,
  x INT DEFAULT 60,
  y INT DEFAULT 60,
  width INT DEFAULT 280,
  height INT DEFAULT 180,
  color VARCHAR(20) DEFAULT '#e7f1ff',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE attachments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  note_id INT NOT NULL,
  type VARCHAR(20) DEFAULT 'image',
  filename VARCHAR(255) NOT NULL,
  x INT DEFAULT 10,
  y INT DEFAULT 50,
  width INT DEFAULT 200,
  height INT DEFAULT 150,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE note_links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  from_note_id INT NOT NULL,
  to_note_id INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (from_note_id) REFERENCES notes(id) ON DELETE CASCADE,
  FOREIGN KEY (to_note_id) REFERENCES notes(id) ON DELETE CASCADE
) ENGINE=InnoDB;